# Generated by Django 5.1.4 on 2025-01-28 03:51

from django.db import migrations, models

def rename_period_choices(apps, schema_editor):
    Plan = apps.get_model('api', 'Plan')
    for instance in Plan.objects.all():
        if instance.period == 'monthly':
            instance.period = 'month'
        elif instance.period == 'yearly':
            instance.period = 'year'
        elif instance.period == 'weekly':
            instance.period = 'week'
        instance.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='period',
            field=models.CharField(choices=[('month', 'Month'), ('year', 'Year'), ('week', 'Week')], max_length=50),
        ),
    ]
