# Generated by Django 5.1.4 on 2025-02-08 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userplan_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userplan',
            old_name='last_used',
            new_name='last_updated',
        ),
    ]
