# Generated by Django 5.1.4 on 2025-02-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_last_used_userplan_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplan',
            name='screen_time',
        ),
        migrations.AddField(
            model_name='userplan',
            name='average_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userplan',
            name='track_usage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userplan',
            name='usage_score',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
    ]
