# Generated by Django 5.1.4 on 2025-02-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_userplan_screen_time_userplan_average_usage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplan',
            name='usage_score',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
    ]
