# Generated by Django 5.1.4 on 2025-02-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_userplan_usage_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
