# Generated by Django 5.1.4 on 2025-02-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_allow_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
