# Generated by Django 5.1.4 on 2025-02-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userplan_next_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='period',
            field=models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('quarter', 'Quarter'), ('year', 'Year')], max_length=50),
        ),
    ]
