# Generated by Django 5.1.4 on 2025-02-18 21:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_plan_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplan',
            name='next_payment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
