# Generated by Django 5.1.4 on 2025-02-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_userplan_next_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='advance_period',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='user',
            name='unused_threshold',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=3),
        ),
    ]
