# Generated by Django 5.1.4 on 2025-02-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_advance_period_user_unused_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='period',
            field=models.CharField(choices=[('one-time', 'One Time'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('quarter', 'Quarter'), ('year', 'Year')], max_length=50),
        ),
    ]
