# Generated by Django 5.1.4 on 2025-02-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_plan_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='period',
            field=models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('quarter', 'Quarter'), ('year', 'Year')], max_length=50),
        ),
    ]
