# Generated by Django 5.1.4 on 2025-02-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_plan_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='free_trial',
            field=models.BooleanField(default=False),
        ),
    ]
