# Generated by Django 5.1.4 on 2025-02-19 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_plan_free_trial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userplan',
            old_name='next_payment_date',
            new_name='payment_date',
        ),
    ]
