# Generated by Django 5.1.4 on 2025-02-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_next_payment_date_userplan_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='total_spent',
            field=models.IntegerField(default=0),
        ),
    ]
