# Generated by Django 5.1.4 on 2025-02-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_userplan_total_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='icon_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
