# Generated by Django 5.1.4 on 2025-02-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_subscription_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='icon_url',
            field=models.URLField(default='https://icons.veryicon.com/png/o/business/settlement-platform-icon/default-16.png'),
        ),
    ]
