# Generated by Django 5.1.4 on 2025-03-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_subscription_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='period',
            field=models.IntegerField(choices=[(1, 'Day'), (7, 'Week'), (30, 'Month'), (90, 'Quarter'), (365, 'Year')]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='usage_score',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
    ]
