# Generated by Django 5.1.4 on 2025-03-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_plan_period_alter_userplan_usage_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='period',
            field=models.IntegerField(choices=[(1, 'Day'), (7, 'Week'), (30, 'Month'), (90, 'Quarter'), (365, 'Year')], default=30),
        ),
    ]
