# Generated by Django 5.1.4 on 2025-03-02 06:50

from django.db import migrations


def set_default_period(apps, schema_editor):
    Plan = apps.get_model("api", "Plan")

    Plan.objects.update(period=30)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_alter_plan_period"),
    ]

    operations = [
        migrations.RunPython(set_default_period),
    ]
