# Generated by Django 5.1.4 on 2025-03-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_update_plan_periods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='period',
            field=models.IntegerField(choices=[(1, 'day'), (7, 'week'), (30, 'month'), (90, 'quarter'), (365, 'year')], default=30),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='usage_score',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1),
        ),
    ]
