# Generated by Django 5.1.4 on 2025-03-04 03:35

from django.db import migrations


def update_usage_scores(apps, schema_editor):
    UserPlan = apps.get_model("api", "UserPlan")
    UserPlan.objects.filter(usage_score=0).update(usage_score=1)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_alter_plan_period_alter_userplan_usage_score"),
    ]

    operations = [
        migrations.RunPython(update_usage_scores),
    ]
