# Generated by Django 5.1.4 on 2025-03-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_update_usage_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_emoji',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
