# Generated by Django 5.1.4 on 2025-03-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_category_icon_emoji'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userplan',
            options={'ordering': ['plan__name']},
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(default='https://i.sstatic.net/l60Hf.png'),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='usage_score',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1),
        ),
    ]
